---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    If Isaiah (I don't know his last name, he's the biology master's student) doesn't earn an A, then nobody should, because I was impressed that although he had never done programming, he was a great programmer in that he didn't just rush into typing things and was quickly understanding the functions we used, for what purpose, and how they worked.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    I think that pivoting has just been the most difficult topic, because I understand it at the level of being able to recognize when it is needed, and which kind, but I have a hard time with the arguments sometimes.

3.  What was the easiest part of the class for you? Explain why.

    I think most of the dplyr things because I have taken classes with pandas, SQL, and other classes where I've used R, and I think the purpose of all of those actions (select, filter, etc.) have been covered enough times where it is now second nature.

4.  What part of the class surprised or interested you the most? Explain why.

    The most interesting part of the class was probably the table creation, because the people who wrote the gt and kable packages really enabled the user to do so many different things and make so many big or small adjustments to their table.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    I think starting the lab as early as possible so as to give yourself room to really read through documentation and stumble across other information in pursuit of the function you're looking for is the best way to go.
