---
title: "The Power of Efficiency"
format: html
editor: visual
---

## The Power of Efficiency

As we’ve said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term “efficiency” means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Include: What is the definition of “efficiency”? What does efficiency look like in statistical computing / data science? What does efficiency allow you to do? Why is efficiency important? Where did you encounter efficiency, and what were some “a-ha” moments you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

The Otis definition of efficiency in terms of statistical computing is code that does its job, and doesn't leave room for unnecessary functionality, minimizes lines, and function calls. I have definitely encountered this multiple times in my subconscious obsession to save objects when I just want one piece of information from a dataframe i will leave unchanged. Efficiency helps our code to run quicker, so we are not using unnecessary resources on functionality that we don't need. It also allows you to type less (generally)! I've definitely encountered inefficiency in many of my many instances while being on an object-saving spree. This allowed me to see why the efficient solution was best, like in my first example in R-3, where I just used a simple filter and an `if_any()` check. My original idea for the solution was a monster in checking for the existence of NAs in each column, but in a much more 'manual' way than the `if_any()` call to each column, and checking if every single one was NA through the `.fns = ~ is.na(.x)` argument. In my case, the efficiency in my code came from taking my time to writing the solution, and ensuring I was taking the best (most efficient!) route to the solution.
